server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://183.131.151.13:3306/lalala
        username: imeeting
        password: ysz123$
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lantw.demo.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql